name: Django Collectstatic

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Collectstatic
      env:        
          DJANGO_SUPERUSER_EMAIL: admin@admin.com
          DJANGO_SUPERUSER_USERNAME: admin
          DJANGO_SUPERUSER_PASSWORD: admin1234
          DJANGO_SECRET_KEY: bad-key
          DJANGO_ADMIN_URL: admin/
          DJANGO_ALLOWED_HOSTS: localhost
          DJANGO_DEBUG: 1
          DJANGO_LIVE: 0
          DATABASE_NAME: mydb
          DATABASE_USER: root
          DATABASE_PASSWORD: root
          DATABASE_HOST: localhost
          DATABASE_PORT: 5432
          EMAIL_HOST_USER: localhost
          EMAIL_HOST_PASSWORD: localhost
      run: |
        python manage.py collectstatic --noinput
